///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SearchCity {
/*
{
  "id": 686542,
  "name": "`Ezbet Saini Tutungi",
  "region": "Al Qahirah",
  "country": "Egypt",
  "lat": 30.14,
  "lon": 31.37,
  "url": "ezbet-saini-tutungi-al-qahirah-egypt"
}
*/

  int? id;
  String? name;
  String? region;
  String? country;
  double? lat;
  double? lon;
  String? url;

  SearchCity({
    this.id,
    this.name,
    this.region,
    this.country,
    this.lat,
    this.lon,
    this.url,
  });
  SearchCity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    region = json['region']?.toString();
    country = json['country']?.toString();
    lat = json['lat']?.toDouble();
    lon = json['lon']?.toDouble();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['region'] = region;
    data['country'] = country;
    data['lat'] = lat;
    data['lon'] = lon;
    data['url'] = url;
    return data;
  }
}
